blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Пример роута без авторизации
//Route::get('sbytnr0fwr1tdvvnh0kr5ln1', 'PlaceController@test')->name('test');

use App\Mail\TestAmazonSes;
use Illuminate\Support\Facades\Mail;

Auth::routes();

Route::group([
    'middleware' => 'auth',
], function () {

});

Route::group([
    'as' => 'blog.'
],
    function () {
        Route::get('/article_layout', 'BlogController@show_article_layout')->name('show_article_layout');
//        Route::get('/', 'BlogController@show')->name('home');
        Route::get('/', 'StaticController@about_me')->name('home');
        Route::get('/blog', 'BlogController@show')->name('blog');
        Route::get('/sitemap.xml', 'BlogController@sitemap')->name('sitemap');
        Route::get('/article_{article_text_url}', 'BlogController@show_article')->name('show_article');
        Route::get('/blog_section_{blog_section_name}', 'BlogController@show_blog_section')->name('show_blog_section');
        Route::post('/add-comment', 'BlogController@add_comment')->name('add_comment_post');
        Route::post('/add-subscriber', 'BlogController@add_subscriber')->name('add_subscriber');
        Route::get('/confirm-subscriber-{hash}', 'BlogController@confirmed_subscriber')->name('confirmed_subscriber');
    }
);

Route::group([
    'as' => 'static_pages.'
],
    function () {
        Route::get('/about_me', 'StaticController@about_me')->name('about_me');
    }
);

Route::group([
    'as' => 'utility.'
],
    function () {
        Route::get('/confirm_subscriber_{email}', 'BlogController@confirm_subscriber')->name('confirm_subscriber');
    }
);

Route::group([
    'as' => 'test.'
],
    function () {
        Route::get('/test_nav', 'TestController@show_nav')->name('nav');
        Route::get('/test_modals', 'TestController@show_modals')->name('modals');
        Route::get('/test_article', 'TestController@show_article_test')->name('article_test');
        Route::get('/test_aws', 'TestController@test_aws')->name('aws_test');
        Route::get('/test_mailing_lists_confirmation',
            'TestController@test_view_mailing_lists_confirmation')->name('mailing_lists_confirmation_test');

    }
);

Route::group([
    'as' => 'docs.'
],
    function () {
        Route::get('/terms-of-use', 'DocsController@show_terms_of_use')->name('terms_of_use');
    }
);


//Route::get('/', 'IndexController@show')->name('main');
//Route::get('/blog', 'BlogController@show')->name('test');


//facebook auth hyytdfndkjnfgdfjkgndfkjgndkjfgndkjfgn
Route::get('/redirect-{whereback}', 'SocialAuthFacebookController@redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');


//Route::get('/home', 'HomeController@index')->name('home');

blog/app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Request;
use Illuminate\Support\Facades\Auth;
use Jenssegers\Agent\Agent;

class Article extends Model
{
    protected $fillable = [
        'title',
        'user_id',
        'seo_description',
        'content',
        'views_count',
        'likes_count',
        'blog_section_id',
    ];

    /**
     * Get the author of the post.
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function blog_section()
    {
        return $this->belongsTo('App\BlogSection');
    }

    public function get_nice_time_created()
    {
        return MyTime::new_time($this->created_at);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function get_comments_counter()
    {
        return Comment::where(['article_id' => $this->id])->count();
    }

    public function viewsArticles()
    {
        return $this->hasMany(ViewArticle::class);
    }

    public function tweetHrefGenerate()
    {
        $result = "https://twitter.com/intent/tweet?text=";
        $result .= $this->title;
        $result .= " ";
        $result .= route('blog.show_article', $this->text_url);
        return $result;
    }

    public function views_update()
    {

        $thisIp = Request::ip();
        $isAuth = Auth::check();

        if ($isAuth) {

            // авторизованный пользователь

            $user_id = Auth::id();

            $thisUserViews = ViewArticle::where([
                'article_id' => $this->id,
                'user_id' => $user_id,
            ])->count();

            if ($thisUserViews == 0) {
                // этот пользователь еще не просматривал данную статью
                $this->views_count++;
                $this->save();
                $this->viewsArticles()->create([
                    'user_id' => $user_id,
                    'ip' => $thisIp,
                ]);
            } else {
                // этот пользователь уже просматривал данную статью
                return true;
            }

        } else {

            //не авторизованный пользователь

            $thisIpViews = ViewArticle::where([
                'article_id' => $this->id,
                'ip' => $thisIp,
            ])->count();

            if ($thisIpViews == 0) {
                // этот пользователь еще не просматривал данную статью
                $this->views_count++;
                $this->save();
                $this->viewsArticles()->create([
                    'ip' => $thisIp,
                ]);
            } else {
                return true;
            }
        }

        return true;

    }

    public static function getRandomLink()
    {
        $allLinks = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=', 'link')->get();
        $randomNumber = random_int(0, count($allLinks) - 1);
        return $allLinks[$randomNumber];
    }

    public static function getRandomArticles($quantity = 2, $article_id)
    {
        $allArticles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=', 'article')->limit(100)->get();


        $full = false;
        while ($full == false):
            $randomNumber = random_int(0, count($allArticles) - 1);
            if ($allArticles[$randomNumber]->id != $article_id) {
                $random_articles[] = $allArticles[$randomNumber];
                break;
            }
        endwhile;


        $full = false;
        $count = 1;

        while ($full == false):

            if ($full) {

                break;

            } else {

                $randomNumber = random_int(0, count($allArticles) - 1);

                for ($i = 0; $i < count($random_articles); $i++) {

                    if ($random_articles[$i]->id == $allArticles[$randomNumber]->id || $allArticles[$randomNumber]->id == $article_id) {
                        continue;
                    }

                    $random_articles[] = $allArticles[$randomNumber];
                    $count++;

                    if ($count == $quantity) {
                        $full = true;
                    }

                }
            }
        endwhile;

        return $random_articles;

    }

    public function isMobile()
    {
        $agent = new Agent();
        return $agent->isMobile();
    }

}

blog/app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\BlogSection;
use App\Comment;
use App\Http\Requests\CommentRequest;
use App\Layout;
use App\Mailing;
use App\Http\Requests\MailingRequest;
use Illuminate\Support\Facades\URL;

class BlogController extends Controller
{
    /**
     * Show the main page.
     *
     * @param int $id
     * @return View
     */
    public function show()
    {
//        echo phpinfo();die();
//        $articles = Article::orderBy('created_at', 'desc')->where('type_article', '=', 'article')->get();
        $articles = Article::orderBy('views_count', 'desc')->where('type_article', '=', 'article')->where('confirmed',
            '=', '1')->get();
//        $items = Article::orderBy('created_at', 'desc')->get();
        $items = Article::orderBy('views_count', 'desc')->where('confirmed',
            '=', '1')->get();
        $top_articles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(4)->get();
        $last_articles = Article::orderBy('views_count', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(2)->get();
        $active_menu_item = 'Блог';
//        return view('blog.index_sidebar',
//            compact('articles', 'top_articles', 'last_articles', 'items', 'request', 'active_menu_item'));
        return view('blog.index_sidebar',
            compact('articles', 'top_articles', 'last_articles', 'items', 'active_menu_item'));
    }

    public function show_article($article_text_url)
    {
        $article = Article::where('text_url', '=', $article_text_url)->where('confirmed',
            '=', '1')->firstOrFail();
        $article->views_update();
        $commentsHtml = Comment::getAllCommentsHtml($article);

        $last_articles = Article::orderBy('views_count', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(2)->get();

        $random_link = Article::getRandomLink();
//        $random_articles = Article::getRandomArticles(2, $article->id);
//        echo phpinfo();die();
        $active_menu_item = 'Блог_статья';
//        return view('blog.article',
//            compact('article', 'commentsHtml', 'last_articles', 'random_link', 'random_articles', 'active_menu_item'));
        return view('blog.article',
            compact('article', 'commentsHtml', 'last_articles', 'random_link', 'active_menu_item'));
    }

    public function show_blog_section($blog_section_name)
    {
        $blog_section = BlogSection::where('title', '=', $blog_section_name)->firstOrFail();
        $articles = Article::orderBy('views_count', 'desc')->where('confirmed',
            '=', '1')->where('blog_section_id', '=', $blog_section->id)->get();
        $items = $articles;
        $top_articles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(4)->get();
        $last_articles = Article::orderBy('views_count', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(2)->get();
        $active_menu_item = 'Блог';
        return view('blog.index_sidebar_blog_section',
            compact('articles', 'top_articles', 'last_articles', 'items', 'request', 'active_menu_item',
                'blog_section'));
    }

    public function show_article_layout()
    {
        $article = Article::where('text_url', '=',
            'praktika_primenenia_burn_down_charts_v_kontekste_safe_i_scrum')->firstOrFail();
        $last_articles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(2)->get();
        $random_link = Article::getRandomLink();
        $random_articles = Article::getRandomArticles(2, 1);
        $active_menu_item = 'Блог_статья';
        return view('blog.article_layout',
            compact('article', 'last_articles', 'random_link', 'random_articles', 'active_menu_item'));
    }

    public function show_old()
    {
        return view('blog.index_sidebar');
    }

    public function add_comment(CommentRequest $request)
    {
        if ($comment = Comment::createComment($request)) {
            return redirect(route('blog.show_article', $request->article_text_url) . "#comment_" . $comment->id);
        }
    }

    public function add_subscriber(MailingRequest $request)
    {

        if ($subscriber = Mailing::createSubscriber($request)) {
            return redirect(route('utility.confirm_subscriber', $subscriber->email));
        }
    }

    public function confirm_subscriber($email)
    {

        $last_articles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(2)->get();
        $active_menu_item = '';
        return view('utility.confirmation_mailing_lists', compact('email', 'last_articles', 'active_menu_item'));
    }

    public function confirmed_subscriber($hash)
    {

        if ($subscriber = Mailing::where([
            ['url', '=', $hash],
            ['confirmed', '=', 0],
        ])->firstOrFail()) {
            $subscriber->confirmed = 1;
            if ($subscriber->save()) {
                $subscriber->send_the_final_confirmation();
            }
            $last_articles = Article::orderBy('created_at', 'desc')->where('confirmed',
                '=', '1')->where('type_article', '=',
                "article")->limit(2)->get();
            $active_menu_item = '';
            return view('utility.confirmed_mailing_lists', compact('subscriber', 'last_articles', 'active_menu_item'));
        }
    }

    public function sitemap()
    {
        $articles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=', 'article')->get();
        return view('blog.sitemap')->with(compact('articles'));
    }
}

blog/resources/views/blog/articles/advertising.blade.php
<div class="sticky-top">
{{--        <a href="#"--}}
    {{--           class="bg-primary-3-alt rounded p-4 d-flex align-items-center justify-content-center min-vh-30">--}}
    {{--            <span class="text-small text-primary-3">Место для вашей рекламы</span>--}}
    {{--        </a>--}}
{{--    @include('blog.articles.mailing_lists')--}}
    @include('blog.articles.popular')

</div>

blog/resources/views/blog/articles/emailing_list_footer.blade.php
<section class="pt-0">
    <div id="mailings_conteiner_for_footer" class="container">
        <div class="row justify-content-center text-center">
            <div class="col-xl-7 col-lg-8 col-md-10">
                <h3 class="h2 mb-5">Получайте новости о новых публикациях прямо на свой email</h3>

                <form action="{{route('blog.add_subscriber')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="d-sm-flex flex-column flex-sm-row mb-3 justify-content-center">
                        <input type="email" name="email" class="mr-sm-1 mb-2 mb-sm-0 form-control form-control-lg"
                               placeholder="Email" required>

                        <div data-recaptcha data-sitekey="INSERT_YOUR_RECAPTCHA_V2_SITEKEY_HERE"
                             data-size="invisible"
                             data-badge="bottomleft"></div>

                        <button type="submit" class="ml-sm-1 btn btn-lg btn-primary btn-loading"
                                data-loading-text="Sending">
                            <img class="icon" src="assets/img/icons/theme/code/loading.svg" alt="loading icon"
                                 data-inject-svg/>
                            <span>Подписаться</span>
                        </button>

                    </div>
                    <div>
                        <div class="d-none alert alert-success" role="alert" data-success-message>
                            Спасибо за ваш интерес, мы отправили вам на почту ссылку для подтверждения Она актуальна в течение
                            24 часов.
                        </div>
                        <div class="d-none alert alert-danger" role="alert" data-error-message>
                            Пожалуйста, используйте валидный email.
                        </div>
                    </div>
                </form>

                <div class="text-small text-muted">
                   Мы никогда не передадим ваши данные третим лицам.
                    <br class="visible-md"/>Посмотрите наши <a target="_blank"
                                                               href="{{route('docs.terms_of_use')}}">Пользовательское соглашение</a> и <a
                            target="_blank"
                            href="{{route('docs.terms_of_use')."#support"}}">Политику Конфиденциальности</a> для более подробной информации.
                </div>
            </div>
        </div>
    </div>
</section>

blog/resources/views/blog/articles/list_items.blade.php
<div class="col-md-8 col-lg-9">


    @for($i=0; $i < count($items); $i++)


        @switch($items[$i]->type_article)
            @case('article')
            <div class="pr-lg-4">
                <div class="card card-article-wide flex-md-row no-gutters">
                    <a href="{{route('blog.show_article',$items[$i]->text_url)}}" class="col-md-4">
                        <img src="{{$items[$i]->main_image_path}}" alt="Image" class="card-img-top">
                    </a>
                    <div class="card-body d-flex flex-column col-auto p-4">
                        <div class="d-flex justify-content-between mb-3">
                            <div class="text-small d-flex">
                                <div class="mr-2">
                                    <a href="{{route('blog.show_blog_section',$items[$i]->blog_section->title)}}">{{$items[$i]->blog_section->title}}</a>
                                </div>
                                <span class="text-muted">{{$items[$i]->get_nice_time_created()}}</span>
                            </div>
                            <span class="badge bg-primary-alt text-primary" data-toggle="tooltip" data-placement="top"
                                  title
                                  data-original-title="Количество уникальных просмотров">
                      <img class="icon icon-sm bg-primary" src="assets/my_svg/Eye_view_views_enable_watch_1886932.svg"
                           alt="heart interface icon" data-inject-svg/>{{$items[$i]->views_count}}
                    </span>
                        </div>
                        <a href="{{route('blog.show_article',$items[$i]->text_url)}}" class="flex-grow-1">
                            <h3>{{$items[$i]->title}}</h3>
                        </a>
                        <div class="d-flex align-items-center mt-3">
                            <img src="{{env('APP_URL').$items[$i]->user->avatar_path}}" alt="Image"
                                 class="avatar avatar-sm">
                            <div class="ml-1">
                                <span class="text-small">{{$items[$i]->user->name}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @break
            @case('link')
            <div class="pr-lg-4">
                <noindex><a rel="nofollow" href="{{$items[$i]->text_url}}"
                            class="card card-body justify-content-between bg-primary text-light">
                        <div class="d-flex justify-content-between mb-3">
                            <div class="text-small d-flex">
                                <div class="mr-2">
                                    Ссылки
                                </div>
                                <span class="opacity-70">{{$items[$i]->get_nice_time_created()}}</span>
                            </div>
                            {{--                        <span class="badge bg-primary-alt text-primary">--}}
                            {{--                    <img class="icon icon-sm bg-primary" src="assets/my_svg/Eye_view_views_enable_watch_1886932.svg"--}}
                            {{--                         alt="heart interface icon" data-inject-svg="">{{$items[$i]->views_count}}--}}
                            {{--                  </span>--}}
                        </div>
                        <div>
                            <h2>{{$items[$i]->title}}</h2>
                            <span class="text-small opacity-70">{{$items[$i]->text_url}}</span>
                        </div>
                    </a></noindex>
            </div>
            @break
            @case('qoute')
            <div class="pr-lg-4">
                <div class="card card-body justify-content-between bg-primary-2 text-light">
                    <div class="d-flex justify-content-between mb-3">
                        <div class="text-small d-flex">
                            <div class="mr-2">
                                <a href="#">Цитаты</a>
                            </div>
                            <span class="opacity-70">{{$items[$i]->get_nice_time_created()}}</span>
                        </div>
                        {{--                        <span class="badge bg-primary text-light">--}}
                        {{--                    <img class="icon icon-sm bg-white" src="assets/my_svg/Eye_view_views_enable_watch_1886932.svg"--}}
                        {{--                         alt="heart interface icon" data-inject-svg="">{{$items[$i]->views_count}}--}}
                        {{--                  </span>--}}
                    </div>
                    <div>
                        <h2>&#171;{{$items[$i]->title}}&#187;</h2>
                        <span class="text-small opacity-70">– {{$items[$i]->first_paragraph}}</span>
                    </div>
                </div>
            </div>
            @break
            @default
            <div></div>
        @endswitch
    @endfor
</div>

blog/resources/views/blog/articles/mailing_lists.blade.php
<div class="mb-4">
    <h5>Новости о новых публикациях</h5>

    <form action="{{route('blog.add_subscriber')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-row">
            <div class="col-12">
                <input type="email" class="form-control mb-2" placeholder="Email" name="email"
                       required>
            </div>
            <div class="col-12">
                <div class="d-none alert alert-success" role="alert" data-success-message>
                    Спасибо за ваш интерес, мы отправили вам на почту ссылку для подтверждения Она актуальна в течение
                    24 часов.
                </div>
                <div class="d-none alert alert-danger" role="alert" data-error-message>
                    Пожалуйста, используйте валидный email.
                </div>
                <div data-recaptcha data-sitekey="INSERT_YOUR_RECAPTCHA_V2_SITEKEY_HERE"
                     data-size="invisible" data-badge="bottomleft">
                </div>
                <button type="submit" class="btn btn-primary btn-loading btn-block"
                        data-loading-text="Sending">
                    <img class="icon" src="assets/img/icons/theme/code/loading.svg"
                         alt="loading icon"
                         data-inject-svg/>
                    <span>Подписаться</span>
                </button>
            </div>
        </div>
    </form>


{{--    <form action="/forms/mailchimp.php" data-form-email novalidate>--}}
{{--        <div class="form-row">--}}
{{--            <div class="col-12">--}}
{{--                <input type="email" class="form-control mb-2" placeholder="Email" name="email"--}}
{{--                       required>--}}
{{--            </div>--}}
{{--            <div class="col-12">--}}
{{--                <div class="d-none alert alert-success" role="alert" data-success-message>--}}
{{--                    Спасибо за ваш интерес, мы отправили вам на почту ссылку для подтверждения Она актуальна в течение--}}
{{--                    24 часов.--}}
{{--                </div>--}}
{{--                <div class="d-none alert alert-danger" role="alert" data-error-message>--}}
{{--                    Пожалуйста, используйте валидный email.--}}
{{--                </div>--}}
{{--                <div data-recaptcha data-sitekey="INSERT_YOUR_RECAPTCHA_V2_SITEKEY_HERE"--}}
{{--                     data-size="invisible" data-badge="bottomleft">--}}
{{--                </div>--}}
{{--                <button type="submit" class="btn btn-primary btn-loading btn-block"--}}
{{--                        data-loading-text="Sending">--}}
{{--                    <img class="icon" src="assets/img/icons/theme/code/loading.svg"--}}
{{--                         alt="loading icon"--}}
{{--                         data-inject-svg/>--}}
{{--                    <span>Подписаться</span>--}}
{{--                </button>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </form>--}}
    <small class="text-muted form-text">Мы никогда не раскроем ваши данные. Смотрите наши <a target="_blank"
                                                                                             href="{{route('docs.terms_of_use')}}">Пользовательское
            соглашение</a> и <a
                target="_blank"
                href="{{route('docs.terms_of_use')."#support"}}">Политику Конфиденциальности</a>
    </small>
</div>

blog/resources/views/blog/articles/popular.blade.php
<div class="mb-4">
    <h5>Последнее в блоге</h5>
    <ul class="list-unstyled list-articles">
        @for($i=0; $i < count($top_articles); $i++)
            <li class="row row-tight">
                <a href="{{route('blog.show_article',$top_articles[$i]->text_url)}}"
                   class="col-3">
                    <img src="{{$top_articles[$i]->main_image_path}}" alt="Image" class="rounded">
                </a>
                <div class="col">
                    <a href="{{route('blog.show_article',$top_articles[$i]->text_url)}}">
                        <h6 class="mb-1">{{$top_articles[$i]->title}}</h6>
                    </a>
                    <div class="d-flex text-small">
                        <a href="{{route('blog.show_blog_section',$top_articles[$i]->blog_section->title)}}">{{$top_articles[$i]->blog_section->title}}</a>
                        <span class="text-muted ml-1">{{$top_articles[$i]->get_nice_time_created()}}</span>
                    </div>
                </div>
            </li>
        @endfor
    </ul>
</div>