blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Пример роута без авторизации
//Route::get('sbytnr0fwr1tdvvnh0kr5ln1', 'PlaceController@test')->name('test');

use App\Mail\TestAmazonSes;
use Illuminate\Support\Facades\Mail;

Auth::routes();

Route::group([
    'middleware' => 'auth',
], function () {

});

Route::group([
    'as' => 'blog.'
],
    function () {
        Route::get('/article_layout', 'BlogController@show_article_layout')->name('show_article_layout');
//        Route::get('/', 'BlogController@show')->name('home');
        Route::get('/', 'StaticController@about_me')->name('home');
        Route::get('/blog', 'BlogController@show')->name('blog');
        Route::get('/sitemap.xml', 'BlogController@sitemap')->name('sitemap');
        Route::get('/article_{article_text_url}', 'BlogController@show_article')->name('show_article');
        Route::get('/blog_section_{blog_section_name}', 'BlogController@show_blog_section')->name('show_blog_section');
        Route::post('/add-comment', 'BlogController@add_comment')->name('add_comment_post');
        Route::post('/add-subscriber', 'BlogController@add_subscriber')->name('add_subscriber');
        Route::get('/confirm-subscriber-{hash}', 'BlogController@confirmed_subscriber')->name('confirmed_subscriber');
    }
);

Route::group([
    'as' => 'static_pages.'
],
    function () {
        Route::get('/about_me', 'StaticController@about_me')->name('about_me');
    }
);

Route::group([
    'as' => 'utility.'
],
    function () {
        Route::get('/confirm_subscriber_{email}', 'BlogController@confirm_subscriber')->name('confirm_subscriber');
    }
);

Route::group([
    'as' => 'test.'
],
    function () {
        Route::get('/test_nav', 'TestController@show_nav')->name('nav');
        Route::get('/test_modals', 'TestController@show_modals')->name('modals');
        Route::get('/test_article', 'TestController@show_article_test')->name('article_test');
        Route::get('/test_aws', 'TestController@test_aws')->name('aws_test');
        Route::get('/test_mailing_lists_confirmation',
            'TestController@test_view_mailing_lists_confirmation')->name('mailing_lists_confirmation_test');

    }
);

Route::group([
    'as' => 'docs.'
],
    function () {
        Route::get('/terms-of-use', 'DocsController@show_terms_of_use')->name('terms_of_use');
    }
);


//Route::get('/', 'IndexController@show')->name('main');
//Route::get('/blog', 'BlogController@show')->name('test');


//facebook auth hyytdfndkjnfgdfjkgndfkjgndkjfgndkjfgn
Route::get('/redirect-{whereback}', 'SocialAuthFacebookController@redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');


//Route::get('/home', 'HomeController@index')->name('home');

blog/app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Request;
use Illuminate\Support\Facades\Auth;
use Jenssegers\Agent\Agent;

class Article extends Model
{
    protected $fillable = [
        'title',
        'user_id',
        'seo_description',
        'content',
        'views_count',
        'likes_count',
        'blog_section_id',
    ];

    /**
     * Get the author of the post.
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function blog_section()
    {
        return $this->belongsTo('App\BlogSection');
    }

    public function get_nice_time_created()
    {
        return MyTime::new_time($this->created_at);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function get_comments_counter()
    {
        return Comment::where(['article_id' => $this->id])->count();
    }

    public function viewsArticles()
    {
        return $this->hasMany(ViewArticle::class);
    }

    public function tweetHrefGenerate()
    {
        $result = "https://twitter.com/intent/tweet?text=";
        $result .= $this->title;
        $result .= " ";
        $result .= route('blog.show_article', $this->text_url);
        return $result;
    }

    public function views_update()
    {

        $thisIp = Request::ip();
        $isAuth = Auth::check();

        if ($isAuth) {

            // авторизованный пользователь

            $user_id = Auth::id();

            $thisUserViews = ViewArticle::where([
                'article_id' => $this->id,
                'user_id' => $user_id,
            ])->count();

            if ($thisUserViews == 0) {
                // этот пользователь еще не просматривал данную статью
                $this->views_count++;
                $this->save();
                $this->viewsArticles()->create([
                    'user_id' => $user_id,
                    'ip' => $thisIp,
                ]);
            } else {
                // этот пользователь уже просматривал данную статью
                return true;
            }

        } else {

            //не авторизованный пользователь

            $thisIpViews = ViewArticle::where([
                'article_id' => $this->id,
                'ip' => $thisIp,
            ])->count();

            if ($thisIpViews == 0) {
                // этот пользователь еще не просматривал данную статью
                $this->views_count++;
                $this->save();
                $this->viewsArticles()->create([
                    'ip' => $thisIp,
                ]);
            } else {
                return true;
            }
        }

        return true;

    }

    public static function getRandomLink()
    {
        $allLinks = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=', 'link')->get();
        $randomNumber = random_int(0, count($allLinks) - 1);
        return $allLinks[$randomNumber];
    }

    public static function getRandomArticles($quantity = 2, $article_id)
    {
        $allArticles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=', 'article')->limit(100)->get();


        $full = false;
        while ($full == false):
            $randomNumber = random_int(0, count($allArticles) - 1);
            if ($allArticles[$randomNumber]->id != $article_id) {
                $random_articles[] = $allArticles[$randomNumber];
                break;
            }
        endwhile;


        $full = false;
        $count = 1;

        while ($full == false):

            if ($full) {

                break;

            } else {

                $randomNumber = random_int(0, count($allArticles) - 1);

                for ($i = 0; $i < count($random_articles); $i++) {

                    if ($random_articles[$i]->id == $allArticles[$randomNumber]->id || $allArticles[$randomNumber]->id == $article_id) {
                        continue;
                    }

                    $random_articles[] = $allArticles[$randomNumber];
                    $count++;

                    if ($count == $quantity) {
                        $full = true;
                    }

                }
            }
        endwhile;

        return $random_articles;

    }

    public function isMobile()
    {
        $agent = new Agent();
        return $agent->isMobile();
    }

}

blog/app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\BlogSection;
use App\Comment;
use App\Http\Requests\CommentRequest;
use App\Layout;
use App\Mailing;
use App\Http\Requests\MailingRequest;
use Illuminate\Support\Facades\URL;

class BlogController extends Controller
{
    /**
     * Show the main page.
     *
     * @param int $id
     * @return View
     */
    public function show()
    {
//        echo phpinfo();die();
//        $articles = Article::orderBy('created_at', 'desc')->where('type_article', '=', 'article')->get();
        $articles = Article::orderBy('views_count', 'desc')->where('type_article', '=', 'article')->where('confirmed',
            '=', '1')->get();
//        $items = Article::orderBy('created_at', 'desc')->get();
        $items = Article::orderBy('views_count', 'desc')->where('confirmed',
            '=', '1')->get();
        $top_articles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(4)->get();
        $last_articles = Article::orderBy('views_count', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(2)->get();
        $active_menu_item = 'Блог';
//        return view('blog.index_sidebar',
//            compact('articles', 'top_articles', 'last_articles', 'items', 'request', 'active_menu_item'));
        return view('blog.index_sidebar',
            compact('articles', 'top_articles', 'last_articles', 'items', 'active_menu_item'));
    }

    public function show_article($article_text_url)
    {
        $article = Article::where('text_url', '=', $article_text_url)->where('confirmed',
            '=', '1')->firstOrFail();
        $article->views_update();
        $commentsHtml = Comment::getAllCommentsHtml($article);

        $last_articles = Article::orderBy('views_count', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(2)->get();

        $random_link = Article::getRandomLink();
//        $random_articles = Article::getRandomArticles(2, $article->id);
//        echo phpinfo();die();
        $active_menu_item = 'Блог_статья';
//        return view('blog.article',
//            compact('article', 'commentsHtml', 'last_articles', 'random_link', 'random_articles', 'active_menu_item'));
        return view('blog.article',
            compact('article', 'commentsHtml', 'last_articles', 'random_link', 'active_menu_item'));
    }

    public function show_blog_section($blog_section_name)
    {
        $blog_section = BlogSection::where('title', '=', $blog_section_name)->firstOrFail();
        $articles = Article::orderBy('views_count', 'desc')->where('confirmed',
            '=', '1')->where('blog_section_id', '=', $blog_section->id)->get();
        $items = $articles;
        $top_articles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(4)->get();
        $last_articles = Article::orderBy('views_count', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(2)->get();
        $active_menu_item = 'Блог';
        return view('blog.index_sidebar_blog_section',
            compact('articles', 'top_articles', 'last_articles', 'items', 'request', 'active_menu_item',
                'blog_section'));
    }

    public function show_article_layout()
    {
        $article = Article::where('text_url', '=',
            'praktika_primenenia_burn_down_charts_v_kontekste_safe_i_scrum')->firstOrFail();
        $last_articles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(2)->get();
        $random_link = Article::getRandomLink();
        $random_articles = Article::getRandomArticles(2, 1);
        $active_menu_item = 'Блог_статья';
        return view('blog.article_layout',
            compact('article', 'last_articles', 'random_link', 'random_articles', 'active_menu_item'));
    }

    public function show_old()
    {
        return view('blog.index_sidebar');
    }

    public function add_comment(CommentRequest $request)
    {
        if ($comment = Comment::createComment($request)) {
            return redirect(route('blog.show_article', $request->article_text_url) . "#comment_" . $comment->id);
        }
    }

    public function add_subscriber(MailingRequest $request)
    {

        if ($subscriber = Mailing::createSubscriber($request)) {
            return redirect(route('utility.confirm_subscriber', $subscriber->email));
        }
    }

    public function confirm_subscriber($email)
    {

        $last_articles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=',
            "article")->limit(2)->get();
        $active_menu_item = '';
        return view('utility.confirmation_mailing_lists', compact('email', 'last_articles', 'active_menu_item'));
    }

    public function confirmed_subscriber($hash)
    {

        if ($subscriber = Mailing::where([
            ['url', '=', $hash],
            ['confirmed', '=', 0],
        ])->firstOrFail()) {
            $subscriber->confirmed = 1;
            if ($subscriber->save()) {
                $subscriber->send_the_final_confirmation();
            }
            $last_articles = Article::orderBy('created_at', 'desc')->where('confirmed',
                '=', '1')->where('type_article', '=',
                "article")->limit(2)->get();
            $active_menu_item = '';
            return view('utility.confirmed_mailing_lists', compact('subscriber', 'last_articles', 'active_menu_item'));
        }
    }

    public function sitemap()
    {
        $articles = Article::orderBy('created_at', 'desc')->where('confirmed',
            '=', '1')->where('type_article', '=', 'article')->get();
        return view('blog.sitemap')->with(compact('articles'));
    }
}

blog/resources/views/blog/article/add_comment.blade.php
<h5 class="my-4">Добавить комментарий</h5>

@auth

    <form action="{{route('blog.add_comment_post')}}" method="post" enctype="multipart/form-data">
        @csrf
        <input type="hidden" name="article_id" value={{$article->id}}>
        <input type="hidden" name="article_text_url" value={{$article->text_url}}>
        <input type="hidden" name="comment_id" value=0>
        <div class="form-group">
                            <textarea id="add_comment_ta" class="form-control" name="content" rows="7"
                                      style="resize: none;"
                                      placeholder="Вы авторизованы и можете написать комментарий"></textarea>
        </div>
        <div class="d-flex align-items-center justify-content-between">
            <button class="btn btn-primary" type="submit">Отправить</button>
        </div>

    </form>
@endauth

@guest

    <script language="JavaScript">

        function FbAuth() {
            document.location.href = 'https://ampleev.com/redirect-add_comment'
        }

        function show_modal_sign_in() {
            $('#sign-up-modal').modal()
        }

    </script>

    <div class="form-group">
        <textarea onclick="show_modal_sign_in();" class="form-control" name="comment-text" rows="7"
                  placeholder="Ваш комментарий"></textarea>
    </div>

    <div class="d-flex align-items-center justify-content-between">
        <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="comment-form-opt-in">
            <label class="custom-control-label text-small" for="comment-form-opt-in">Оповестить меня
                когда кто-то ответит</label>
        </div>
        <button class="btn btn-primary">Отправить</button>
    </div>

    <div class="modal fade" id="sign-up-modal" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                             class="injected-svg icon bg-dark" data-src="assets/img/icons/interface/cross.svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink">
                            <path d="M16.2426 6.34311L6.34309 16.2426C5.95257 16.6331 5.95257 17.2663 6.34309 17.6568C6.73362 18.0473 7.36678 18.0473 7.75731 17.6568L17.6568 7.75732C18.0473 7.36679 18.0473 6.73363 17.6568 6.34311C17.2663 5.95258 16.6331 5.95258 16.2426 6.34311Z"
                                  fill="#212529"></path>
                            <path d="M17.6568 16.2426L7.75734 6.34309C7.36681 5.95257 6.73365 5.95257 6.34313 6.34309C5.9526 6.73362 5.9526 7.36678 6.34313 7.75731L16.2426 17.6568C16.6331 18.0473 17.2663 18.0473 17.6568 17.6568C18.0474 17.2663 18.0474 16.6331 17.6568 16.2426Z"
                                  fill="#212529"></path>
                        </svg>
                    </button>
                    <div class="m-xl-4 m-3">
                        <div class="text-center mb-4">
                            <h4 class="h3 mb-1">Авторизация</h4>
                            <span>Для добавления комментария необходимо авторизоваться</span>
                        </div>
                        <div class="form-group">
                            <button onclick="FbAuth();" class="btn-block btn btn-primary" type="submit">Войти через
                                facebook
                            </button>
                        </div>
                        <div class="text-center text-small text-muted">
                                <span>Изучите наши <a target="_blank"
                                                      href="{{route('docs.terms_of_use')}}">Пользовательское соглашение</a> и <a
                                            target="_blank"
                                            href="{{route('docs.terms_of_use')."#support"}}">Политику Конфиденциальности</a>. Регистрируясь или авторизуясь, вы автоматически соглашаетесь с ними.
                            </span>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endguest

blog/resources/views/blog/article/answer_form.blade.php
<ol id="form_for_answer" style="display: none;" class="comments">
    <li class="comment">
        <div class="d-flex align-items-center text-small my-answers">
            @auth
                <img src="{{Auth::user()->avatar_path}}" alt="{{Auth::user()->name}}"
                     class="avatar avatar-sm mr-2">
                <div class="text-dark mr-1">{{Auth::user()->name}}</div>
            @endauth
        </div>
        <form action="{{route('blog.add_comment_post')}}" method="post" enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="article_id" value={{$article->id}}>
            <input type="hidden" name="comment_id" value="0">
            <input type="hidden" name="article_text_url" value={{$article->text_url}}>
            <div class="form-group">
                            <textarea class="form-control" name="content" rows="7"
                                      style="resize: none;"
                                      placeholder="Напишите что бы вы хотели ответить.."></textarea>
            </div>
            <div class="d-flex align-items-center justify-content-between">
                <button class="btn btn-primary" type="submit">Отправить</button>
            </div>
        </form>
    </li>
</ol>

blog/resources/views/blog/article/article_progress.blade.php
<div class="article-progress" data-sticky="below-nav">
    <progress class="reading-position" value="0"></progress>
    <div class="article-progress-wrapper">
        <div class="container">
            <div class="row">
                <div class="col py-2">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex">
                            <div class="text-small text-muted mr-1">Читаете:</div>
                            <div class="text-small">{{$article->title}}</div>
                        </div>
                        <div class="d-flex align-items-center">
                            <span class="text-small text-muted">Поделиться:</span>
                            <div class="d-flex ml-1">
                                <a href="{{$article->tweetHrefGenerate()}}"
                                   class="mx-1 btn btn-sm btn-round btn-primary">
                                    <img class="icon" src="assets/img/icons/social/twitter.svg"
                                         alt="twitter social icon" data-inject-svg/>
                                </a>
                                <a href="https://www.facebook.com/sharer/sharer.php?u={{route('blog.show_article', $article->text_url)}}&display=popup"
                                   class="mx-1 btn btn-sm btn-round btn-primary">
                                    <img class="icon" src="assets/img/icons/social/facebook.svg"
                                         alt="facebook social icon" data-inject-svg/>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

blog/resources/views/blog/article/breadcrumb_and_views.blade.php
<section class="pb-0 pb-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10 col-xl-8">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{route('blog.blog')}}">Блог</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{route('blog.show_blog_section',$article->blog_section->title)}}">{{$article->blog_section->title}}</a>
                            </li>
                        </ol>
                    </nav>
                    <span class="badge bg-primary-alt text-primary" data-toggle="tooltip" data-placement="top" title
                          data-original-title="Количество уникальных просмотров">
                <img class="icon bg-primary"
                     src="assets/my_svg/Eye_view_views_enable_watch_1886932.svg"
                     alt="heart interface icon"
                     data-inject-svg/>{{$article->views_count}}</span>
                </div>
                <h1>{{$article->title}}</h1>
                <div class="d-flex align-items-center">
                    <a href="#">
                        <img src="{{env('APP_URL').$article->user->avatar_path}}" alt="Avatar" class="avatar mr-2">
                    </a>
                    <div>
                        <div>Автор статьи: <a href="#">{{$article->user->name}}</a>
                        </div>
                        <div class="text-small text-muted">{{$article->get_nice_time_created()}}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

blog/resources/views/blog/article/comments.blade.php
@if($article->get_comments_counter() > 0)
    <hr>
    <h5 class="my-4">Всего комментариев: {{$article->get_comments_counter()}}</h5>
@endif
{!! $commentsHtml !!}
<script>
    document.addEventListener('click', e => {
        let element = e.target;
        let parent_element = element.parentNode.parentNode;
        // console.log('parent', parent_element);
        if (element.hasAttribute('to_give_an_answer_to_comment')) {
            element.style.display = 'none'; // скрываем кнопку ответить
            let form = document.getElementById('form_for_answer');// получили форму
            parent_element.append(form);
            form.style.display = 'block';
            let element_comment_id = form.firstElementChild.firstElementChild.nextElementSibling.firstElementChild.nextElementSibling.nextElementSibling;
            // console.log(element)
            element_comment_id.setAttribute('value', element.dataset.answer_to_comment_id)
        }
    });
</script>

blog/resources/views/blog/article/related_stories.blade.php
<section class="bg-primary-alt">
    <div class="container">
        <div class="row mb-4">
            <div class="col">
                <h3 class="h2">Возможно, вам будет интересно</h3>
            </div>
        </div>
        <div class="row">

            <div class="col-md-6 col-lg-4 d-flex" data-aos="fade-up" data-aos-delay="100">
                <a rel="nofollow" href="{{$random_link->text_url}}"
                   class="card card-body justify-content-between bg-primary text-light">
                    <div class="d-flex justify-content-between mb-3">
                        <div class="text-small d-flex">
                            <div class="mr-2">
                                Ссылки
                            </div>
                            <span class="opacity-70">{{$random_link->get_nice_time_created()}}</span>
                        </div>
                        {{--                        <span class="badge bg-primary-alt text-primary">--}}
                        {{--                  <img class="icon icon-sm bg-primary" src="assets/my_svg/Eye_view_views_enable_watch_1886932.svg"--}}
                        {{--                       alt="heart interface icon" data-inject-svg/>{{$random_link->views_count}}--}}
                        {{--                </span>--}}
                    </div>
                    <div>
                        <h2>{{$random_link->title}}</h2>
                        <span class="text-small opacity-70">{{$random_link->text_url}}</span>
                    </div>
                </a>
            </div>

{{--            @for($i=0; $i < count($random_articles); $i++)--}}
{{--                <div class="col-md-6 col-lg-4 d-flex" data-aos="fade-up" data-aos-delay="200">--}}
{{--                    <div class="card">--}}
{{--                        <a href="{{route('blog.show_article',$random_articles[$i]->text_url)}}">--}}
{{--                            <img src="{{$random_articles[$i]->main_image_path}}" alt="Image" class="card-img-top">--}}
{{--                        </a>--}}
{{--                        <div class="card-body d-flex flex-column">--}}
{{--                            <div class="d-flex justify-content-between mb-3">--}}
{{--                                <div class="text-small d-flex">--}}
{{--                                    <div class="mr-2">--}}
{{--                                        <a href="#">{{$random_articles[$i]->blog_section->title}}</a>--}}
{{--                                    </div>--}}
{{--                                    <span class="text-muted">{{$random_articles[$i]->get_nice_time_created()}}</span>--}}
{{--                                </div>--}}
{{--                                <span class="badge bg-primary-alt text-primary">--}}
{{--                    <img class="icon icon-sm bg-primary" src="assets/my_svg/Eye_view_views_enable_watch_1886932.svg"--}}
{{--                         alt="heart interface icon" data-inject-svg/>{{$random_articles[$i]->views_count}}--}}
{{--                  </span>--}}
{{--                            </div>--}}
{{--                            <a href="{{route('blog.show_article',$random_articles[$i]->text_url)}}">--}}
{{--                                <h4>{{$random_articles[$i]->title}}</h4>--}}
{{--                            </a>--}}
{{--                            <p class="flex-grow-1">--}}
{{--                                {{$random_articles[$i]->seo_description}}--}}
{{--                            </p>--}}
{{--                            <div class="d-flex align-items-center mt-3">--}}
{{--                                <img src="{{env('APP_URL').$random_articles[$i]->user->avatar_path}}" alt="Image"--}}
{{--                                     class="avatar avatar-sm">--}}
{{--                                <div class="ml-1">--}}
{{--                                    <span class="text-small">{{$random_articles[$i]->user->name}}</span>--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            @endfor--}}
        </div>
    </div>
</section>

blog/resources/views/blog/article/social_sharing.blade.php
<div class="d-flex align-items-center">
    {{--                        <span class="text-small mr-1">Поделиться этой статьей:</span>--}}
    <div class="d-flex mx-2">
        {{--                            <div--}}
        {{--                                    class="fb-like"--}}
        {{--                                    data-share="true"--}}
        {{--                                    data-width="450"--}}
        {{--                                    data-show-faces="true">--}}
        {{--                            </div>--}}
        <a href="https://www.facebook.com/sharer/sharer.php?u={{route('blog.show_article', $article->text_url)}}&display=popup"
           class="btn btn-round btn-primary mx-1">
            <img class="icon icon-sm" src="assets/img/icons/social/facebook.svg"
                 alt="facebook social icon" data-inject-svg/>
        </a>
        <a href="{{$article->tweetHrefGenerate()}}"
           class="btn btn-round btn-primary mx-1">
            <img class="icon icon-sm" src="assets/img/icons/social/twitter.svg"
                 alt="twitter social icon" data-inject-svg/>
        </a>

    </div>
</div>